<template>
  <div>
    ABS:
    1. Outline of Anti-lock Brake System
    Antilock brake system is electronic systems that monitor and control wheel slip during vehicle braking. ABS can improve vehicle control during braking and reduce stopping distances on slippery road surface. An ABS consist electronic control unit (ECU), wheel speed sensor, fail-safe system. This ABS is manufactured by wabco corporation.

    2. Electronic Control Unit (ECU) for ABS
    The ECU processes all ABS information and signal functions, it receives and interprets voltage pulse
    generated by the sensor pickup as the exciter teeth pass by and uses this information to determine impending wheel lock-up.

    3. Wheel Speed Sensor
    the wheel speed sensor has two main components:  the exciter and the pickup. The pickup contains a wire
    coil/magnet assembly. Which generates pulses of electricity as the teeth of the excieter pass in front of it. The ECU uses the pulses to determine wheel.

    4. Fail-safe System
    If the electrical system fails, the ABS is shut off, returning the vehicle to normal braking.
    In case a failure was detected, the ABS warning will be activated.

    5. Control mothod
    4S4M mode

    ESC:
    1.  ESC system
    - Electronic Stability Control (ESC) shall enhance driving safety at cornering by identification and control of critical yaw and rolling conditions like spinning, drifting, jackknifing or roll-over.
    - For this purpose the system comprises means of yaw and roll stability control. In case of critical instabilities automatic control interventions of ESC help to improve the vehicle handling, maintain the direction desired by the driver and restore the driving stability as far as possible within the given physical limits.
    - This product conforms to ECE standards and has been successfully tested and validated on worst-case road with banking angles of up to 6 to 8 degrees and different critical vehicle types. Unique road conditions may cause certain vehicles to experience body roll and road inclination characteristics that may adversely affect the slip angle calculation by the ESC.

    2. ESC system components
    The ESC function requires the following additional components:
    - ABS ECU with two CAN interfaces (vehicle bus CAN2.0B, system bus CAN2.0A)
    - ESC module (at CAN2.0A)
    - Steering angle sensor (at vehicle bus or CAN2.0A)
    - Brake pressure sensor
    - 3/2 Solenoid Valve and double check valve
  </div>
</template>

<script>
  export default {
    name: "annex_8_C_20_tail"
  }
</script>
